import fs from "node:fs/promises";
import path from "node:path";
import { chromium } from "playwright";
const outDir = "F:/성신여자대학교/수업/2026_02/HCI와 커뮤니케이션/retroApp/.codex-build/week4-affordance/screenshots";
await fs.mkdir(outDir, { recursive: true });
const browser = await chromium.launch({ headless: true, executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe" });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
page.on('console', msg => console.log('console', msg.type(), msg.text()));
page.on('pageerror', err => console.log('pageerror', err.message));
await page.goto('http://127.0.0.1:8781/norman/', { waitUntil: 'networkidle', timeout: 15000 });
await page.screenshot({ path: path.join(outDir, '01-team-gate.png'), fullPage: true });
// select team 20
await page.click('.teamcell[data-team="20"]', { timeout: 5000 }).catch(e => console.log('team click failed', e.message));
await page.screenshot({ path: path.join(outDir, '01-team-selected.png'), fullPage: true });
await page.click('#enter', { timeout: 5000 }).catch(e => console.log('enter failed', e.message));
await page.waitForTimeout(2500);
await page.screenshot({ path: path.join(outDir, '02-workbench.png'), fullPage: true });
await page.click('[data-go="shop"]', { timeout: 5000 }).catch(e => console.log('shop failed', e.message));
await page.waitForTimeout(1000);
await page.screenshot({ path: path.join(outDir, '03-shop.png'), fullPage: true });
await page.click('[data-go="bench"]', { timeout: 5000 }).catch(()=>{});
await page.waitForTimeout(500);
await page.locator('#craft').screenshot({ path: path.join(outDir, '04-craft-panel.png') }).catch(async e => { console.log('craft panel failed', e.message); await page.screenshot({ path: path.join(outDir, '04-craft-panel.png'), fullPage: true }); });
await page.click('#cold', { timeout: 5000 }).catch(e => console.log('test failed', e.message));
await page.waitForTimeout(3500);
await page.screenshot({ path: path.join(outDir, '05-test-result.png'), fullPage: true });
await page.click('[data-go="quiz"]', { timeout: 5000 }).catch(e => console.log('quiz failed', e.message));
await page.waitForTimeout(1000);
await page.screenshot({ path: path.join(outDir, '07-quiz.png'), fullPage: true });
// closing overlay trigger if available by simulating local ending state? call function unavailable, so try board page instead
await page.goto('http://127.0.0.1:8781/norman/board.html', { waitUntil: 'networkidle', timeout: 15000 });
await page.screenshot({ path: path.join(outDir, '08-board.png'), fullPage: true });
await browser.close();
console.log(JSON.stringify({ outDir }, null, 2));
