import { FileBlob, PresentationFile } from "@oai/artifact-tool";
const p = await PresentationFile.importPptx(await FileBlob.load("F:/성신여자대학교/수업/2025_02/HCI와 커뮤니케이션/템플릿.pptx"));
const s = p.slides.getItem(1);
console.log('slides keys', Object.keys(p.slides));
console.log('slide keys', Object.keys(s));
console.log('shapes keys', Object.keys(s.shapes));
console.log('images keys', Object.keys(s.images));
console.log('shapes items', Array.isArray(s.shapes.items), s.shapes.items?.length, s.shapes.items?.map(x => ({name:x.name, id:x.id, keys:Object.keys(x).slice(0,10)})));
console.log('images items', Array.isArray(s.images.items), s.images.items?.length, s.images.items?.map(x => ({name:x.name, id:x.id, keys:Object.keys(x).slice(0,10)})));
console.log('slide methods', Object.getOwnPropertyNames(Object.getPrototypeOf(s)).filter(k=>typeof s[k]==='function'));
